// Fichier : /server/src/config/seedLookups.ts
// Script de peuplement initial des lookups P1 et DD (Due Diligence)

import { LookupModel } from '../models/Lookup.model.js';

export async function seedInitialLookups() {
  const lookups = [
    {
      key: 'BUSINESS_CRITICALITY',
      category: 'P1',
      entity: 'Editor',
      formLabel: 'Criticité Métier',
      description: 'Niveaux de criticité métier pour les éditeurs',
      values: [
        { code: 'Low', label: 'Faible', label_fr: 'Faible', label_en: 'Low', description: 'Impact métier limité en cas d\'indisponibilité', order: 1, active: true },
        { code: 'Medium', label: 'Moyenne', label_fr: 'Moyenne', label_en: 'Medium', description: 'Impact métier modéré en cas d\'indisponibilité', order: 2, active: true },
        { code: 'High', label: 'Élevée', label_fr: 'Élevée', label_en: 'High', description: 'Impact métier important en cas d\'indisponibilité', order: 3, active: true },
        { code: 'Critical', label: 'Critique', label_fr: 'Critique', label_en: 'Critical', description: 'Impact métier critique en cas d\'indisponibilité', order: 4, active: true },
      ],
    },
    {
      key: 'SOLUTION_TYPES',
      category: 'P1',
      entity: 'Solution',
      formLabel: 'Mode Logiciel (Type)',
      description: 'Types de solutions/logiciels',
      values: [
        { code: 'SaaS', label: 'Software as a Service', label_fr: 'Logiciel en tant que Service', label_en: 'Software as a Service', description: 'Solution hébergée et accessible via Internet', order: 1, active: true },
        { code: 'OnPrem', label: 'On-Premise', label_fr: 'Sur site', label_en: 'On-Premise', description: 'Solution installée et gérée sur les serveurs du client', order: 2, active: true },
        { code: 'Hybrid', label: 'Hybride', label_fr: 'Hybride', label_en: 'Hybrid', description: 'Combinaison de SaaS et On-Premise', order: 3, active: true },
        { code: 'ClientHeavy', label: 'Client Lourd', label_fr: 'Client Lourd', label_en: 'Client Heavy', description: 'Application nécessitant une installation client importante', order: 4, active: true },
        { code: 'ClientHeavyHosted', label: 'Client Lourd (hébergé)', label_fr: 'Client Lourd (hébergé)', label_en: 'Client Heavy (Hosted)', description: 'Client lourd avec possibilité d\'hébergement', order: 5, active: true },
        { code: 'FullWeb', label: 'Application Web Complète', label_fr: 'Application Web Complète', label_en: 'Full Web Application', description: 'Application web complète accessible via navigateur', order: 6, active: true },
        { code: 'OnPremEditor', label: 'On-Premise (Éditeur)', label_fr: 'On-Premise (Éditeur)', label_en: 'On-Premise (Publisher)', description: 'Solution installée chez l\'éditeur', order: 7, active: true },
        { code: 'OnPremClient', label: 'On-Premise (Client)', label_fr: 'On-Premise (Client)', label_en: 'On-Premise (Client)', description: 'Solution installée chez le client', order: 8, active: true },
        { code: 'ERPAllInOne', label: 'ERP Tout-en-un', label_fr: 'ERP Tout-en-un', label_en: 'ERP All-in-One', description: 'ERP intégré tout-en-un', order: 9, active: true },
      ],
    },
    {
      key: 'DATA_TYPES',
      category: 'P1',
      entity: 'Environment',
      formLabel: 'Types de Données Hébergées',
      description: 'Types de données hébergées',
      values: [
        { code: 'Personal', label: 'Données Personnelles', label_fr: 'Données Personnelles', label_en: 'Personal Data', description: 'Données personnelles soumises au RGPD', order: 1, active: true },
        { code: 'Sensitive', label: 'Données Sensibles', label_fr: 'Données Sensibles', label_en: 'Sensitive Data', description: 'Données sensibles nécessitant une protection renforcée', order: 2, active: true },
        { code: 'Health', label: 'Données de Santé', label_fr: 'Données de Santé', label_en: 'Health Data', description: 'Données de santé soumises à la certification HDS', order: 3, active: true },
        { code: 'Financial', label: 'Données Financières', label_fr: 'Données Financières', label_en: 'Financial Data', description: 'Données financières soumises à des réglementations strictes', order: 4, active: true },
        { code: 'Synthetic', label: 'Données Synthétiques', label_fr: 'Données Synthétiques', label_en: 'Synthetic Data', description: 'Données générées artificiellement (non sensibles)', order: 5, active: true },
      ],
    },
    {
      key: 'REDUNDANCY_LEVELS',
      category: 'P1',
      entity: 'Environment',
      formLabel: 'Niveau de Redondance',
      description: 'Niveaux de redondance pour les environnements',
      values: [
        { code: 'none', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Pas de redondance configurée', order: 1, active: true },
        { code: 'minimal', label: 'Minimale (dégradée)', label_fr: 'Minimale (dégradée)', label_en: 'Minimal (Degraded)', description: 'Redondance minimale avec dégradation possible', order: 2, active: true },
        { code: 'full', label: 'Complète (full perimeter)', label_fr: 'Complète (périmètre complet)', label_en: 'Full (Full Perimeter)', description: 'Redondance complète sur tout le périmètre', order: 3, active: true },
        { code: 'geo-redundant', label: 'Géo-redondante', label_fr: 'Géo-redondante', label_en: 'Geo-redundant', description: 'Redondance géographique (plusieurs datacenters)', order: 4, active: true },
        { code: 'high', label: 'Élevée', label_fr: 'Élevée', label_en: 'High', description: 'Redondance élevée avec failover automatique', order: 5, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 6, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 7, active: true },
      ],
    },
    {
      key: 'AUTH_TYPES',
      category: 'P1',
      entity: 'Security',
      formLabel: 'Authentification',
      description: 'Types d\'authentification',
      values: [
        { code: 'None', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Pas d\'authentification requise', order: 1, active: true },
        { code: 'Passwords', label: 'Mots de passe', label_fr: 'Mots de passe', label_en: 'Passwords', description: 'Authentification par mot de passe simple', order: 2, active: true },
        { code: 'MFA', label: 'Authentification Multi-Facteurs', label_fr: 'Authentification Multi-Facteurs', label_en: 'Multi-Factor Authentication', description: 'Authentification à deux facteurs (2FA/MFA)', order: 3, active: true },
        { code: 'SSO', label: 'Single Sign-On', label_fr: 'Authentification Unique', label_en: 'Single Sign-On', description: 'Authentification unique via un fournisseur d\'identité', order: 4, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 5, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 6, active: true },
      ],
    },
    // ========== LOOKUPS DD (Due Diligence) ==========
    {
      key: 'ENVIRONMENT_TYPES',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Type d\'Environnement',
      description: 'Types d\'environnements (CIEC)',
      values: [
        { code: 'production', label: 'Production', label_fr: 'Production', label_en: 'Production', description: 'Environnement de production', order: 1, active: true },
        { code: 'production_small', label: 'Production (Petits Clients)', label_fr: 'Production (Petits Clients)', label_en: 'Production (Small Clients)', description: 'Production pour petits clients', order: 2, active: true },
        { code: 'production_large', label: 'Production (Grands Clients)', label_fr: 'Production (Grands Clients)', label_en: 'Production (Large Clients)', description: 'Production pour grands clients', order: 3, active: true },
        { code: 'test', label: 'Tests', label_fr: 'Tests', label_en: 'Test', description: 'Environnement de test', order: 4, active: true },
        { code: 'dev', label: 'Développement', label_fr: 'Développement', label_en: 'Development', description: 'Environnement de développement', order: 5, active: true },
        { code: 'dev_local', label: 'Développement Local', label_fr: 'Développement Local (IDE, BDD)', label_en: 'Local Development (IDE, DB)', description: 'Environnement de développement local', order: 6, active: true },
        { code: 'dev_remote', label: 'Développement Distant', label_fr: 'Développement Distant (BDD)', label_en: 'Remote Development (DB)', description: 'Environnement de développement distant', order: 7, active: true },
        { code: 'backup', label: 'Sauvegarde', label_fr: 'Sauvegarde', label_en: 'Backup', description: 'Environnement de sauvegarde', order: 8, active: true },
        { code: 'infrastructure', label: 'Infrastructure Interne', label_fr: 'Infrastructure Interne', label_en: 'Internal Infrastructure', description: 'Infrastructure interne (emails, GED, outils collaboratifs)', order: 9, active: true },
        { code: 'repo', label: 'Repository Source Code', label_fr: 'Repository Source Code', label_en: 'Source Code Repository', description: 'Repository distant pour collaboration et sauvegarde', order: 10, active: true },
        { code: 'recette', label: 'Recette', label_fr: 'Recette', label_en: 'UAT (User Acceptance Testing)', description: 'Environnement de recette pour les tests d\'acceptation utilisateur', order: 11, active: true },
      ],
    },
    {
      key: 'HOSTING_TIERS',
      category: 'DD',
      entity: 'Hosting',
      formLabel: 'Type d\'Hébergement',
      description: 'Types d\'hébergement (CIEC)',
      values: [
        { code: 'onprem_editor', label: 'On-Premise (Éditeur)', label_fr: 'On-Premise (Éditeur)', label_en: 'On-Premise (Publisher)', description: 'Hébergement on-premise chez l\'éditeur', order: 1, active: true },
        { code: 'onprem_client', label: 'On-Premise (Client)', label_fr: 'On-Premise (Client)', label_en: 'On-Premise (Client)', description: 'Hébergement on-premise chez le client', order: 2, active: true },
        { code: 'datacenter_editor', label: 'Datacenter (Éditeur)', label_fr: 'Datacenter (Éditeur)', label_en: 'Datacenter (Publisher)', description: 'Datacenter appartenant à l\'éditeur', order: 3, active: true },
        { code: 'datacenter_private', label: 'Datacenter (Privé)', label_fr: 'Datacenter (Privé)', label_en: 'Private Datacenter', description: 'Datacenter privé', order: 4, active: true },
        { code: 'third_party', label: 'Hébergeur Tiers', label_fr: 'Hébergeur Tiers (OVH, Bleu, Scaleway, etc.)', label_en: 'Third-Party Hosting (OVH, Blue, Scaleway, etc.)', description: 'Hébergement par un tiers (OVH, Bleu, Scaleway, etc.)', order: 5, active: true },
        { code: 'cloud_public', label: 'Cloud Public', label_fr: 'Cloud Public (AWS, Azure, GCP, etc.)', label_en: 'Public Cloud (AWS, Azure, GCP, etc.)', description: 'Cloud public (AWS, Azure, GCP, etc.)', order: 6, active: true },
        { code: 'cloud_hybrid', label: 'Cloud Hybride', label_fr: 'Cloud Hybride', label_en: 'Hybrid Cloud', description: 'Cloud hybride', order: 7, active: true },
        { code: 'internal', label: 'En Interne', label_fr: 'En Interne (chez l\'éditeur)', label_en: 'Internal (at Publisher)', description: 'Hébergement interne chez l\'éditeur', order: 8, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 9, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 10, active: true },
      ],
    },
    {
      key: 'DEPLOYMENT_TYPES',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Type de Déploiement',
      description: 'Types de déploiement (CIEC)',
      values: [
        { code: 'monolith', label: 'Monolithique', label_fr: 'Monolithique', label_en: 'Monolithic', description: 'Architecture monolithique', order: 1, active: true },
        { code: 'microservices', label: 'Microservices', label_fr: 'Microservices', label_en: 'Microservices', description: 'Architecture microservices', order: 2, active: true },
        { code: 'hybrid', label: 'Hybride', label_fr: 'Hybride', label_en: 'Hybrid', description: 'Architecture hybride', order: 3, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 4, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 5, active: true },
      ],
    },
    {
      key: 'VIRTUALIZATION_TYPES',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Virtualisation/Conteneurisation',
      description: 'Types de virtualisation et conteneurisation (CIEC)',
      values: [
        { code: 'physical', label: 'Matériel', label_fr: 'Matériel', label_en: 'Physical', description: 'Serveurs physiques', order: 1, active: true },
        { code: 'vmware', label: 'VMware', label_fr: 'VMware', label_en: 'VMware', description: 'Virtualisation VMware', order: 2, active: true },
        { code: 'docker', label: 'Docker', label_fr: 'Docker', label_en: 'Docker', description: 'Conteneurisation Docker', order: 3, active: true },
        { code: 'kubernetes', label: 'Kubernetes', label_fr: 'Kubernetes', label_en: 'Kubernetes', description: 'Orchestration Kubernetes', order: 4, active: true },
      ],
    },
    {
      key: 'SCALING_MECHANISMS',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Mécanisme de Montée en Charge',
      description: 'Mécanismes de montée en charge (CIEC)',
      values: [
        { code: 'vertical', label: 'Verticale', label_fr: 'Verticale', label_en: 'Vertical', description: 'Montée en charge verticale (augmentation des ressources)', order: 1, active: true },
        { code: 'horizontal', label: 'Horizontale', label_fr: 'Horizontale', label_en: 'Horizontal', description: 'Montée en charge horizontale (ajout d\'instances)', order: 2, active: true },
        { code: 'not_supported', label: 'Non Supportée', label_fr: 'Non Supportée', label_en: 'Not Supported', description: 'Montée en charge non supportée', order: 3, active: true },
      ],
    },
    {
      key: 'MONITORING_STATUS',
      category: 'DD',
      entity: 'MonitoringObservability',
      formLabel: 'Statut de Monitoring',
      description: 'Statuts de monitoring et observabilité (CIEC)',
      values: [
        { code: 'yes_industrial', label: 'Oui (Industriel)', label_fr: 'Oui (Industriel)', label_en: 'Yes (Industrial)', description: 'Monitoring industriel complet', order: 1, active: true },
        { code: 'partial', label: 'Partiel', label_fr: 'Partiel', label_en: 'Partial', description: 'Monitoring partiel', order: 2, active: true },
        { code: 'no', label: 'Non', label_fr: 'Non', label_en: 'No', description: 'Pas de monitoring', order: 3, active: true },
      ],
    },
    {
      key: 'MONITORING_TOOLS',
      category: 'DD',
      entity: 'MonitoringObservability',
      formLabel: 'Outils de Monitoring',
      description: 'Outils de monitoring et observabilité (CIEC) - Choix multiple',
      values: [
        { code: 'prometheus', label: 'Prometheus', label_fr: 'Prometheus (Observabilité hybride)', label_en: 'Prometheus (Hybrid Observability)', description: 'Prometheus pour la collecte de métriques', order: 1, active: true },
        { code: 'grafana', label: 'Grafana', label_fr: 'Grafana (Observabilité hybride)', label_en: 'Grafana (Hybrid Observability)', description: 'Grafana pour la visualisation', order: 2, active: true },
        { code: 'elk', label: 'ELK Stack', label_fr: 'ELK Stack (Elasticsearch, Logstash, Kibana)', label_en: 'ELK Stack (Elasticsearch, Logstash, Kibana)', description: 'Stack ELK pour les logs', order: 3, active: true },
        { code: 'graylog', label: 'Graylog', label_fr: 'Graylog (Observabilité hybride)', label_en: 'Graylog (Hybrid Observability)', description: 'Graylog pour la gestion des logs', order: 4, active: true },
        { code: 'datadog', label: 'Datadog', label_fr: 'Datadog (Monitoring Application et Infrastructure)', label_en: 'Datadog (Application and Infrastructure Monitoring)', description: 'Datadog pour le monitoring complet', order: 5, active: true },
        { code: 'splunk', label: 'Splunk', label_fr: 'Splunk (Monitoring Application et Infrastructure)', label_en: 'Splunk (Application and Infrastructure Monitoring)', description: 'Splunk pour l\'analyse de données', order: 6, active: true },
        { code: 'zabbix', label: 'Zabbix', label_fr: 'Zabbix (Monitoring Application et Infrastructure)', label_en: 'Zabbix (Application and Infrastructure Monitoring)', description: 'Zabbix pour le monitoring réseau', order: 7, active: true },
        { code: 'newrelic', label: 'New Relic', label_fr: 'New Relic (Monitoring Application et Infrastructure)', label_en: 'New Relic (Application and Infrastructure Monitoring)', description: 'New Relic pour l\'APM', order: 8, active: true },
        { code: 'dynatrace', label: 'Dynatrace', label_fr: 'Dynatrace (Monitoring Application et Infrastructure)', label_en: 'Dynatrace (Application and Infrastructure Monitoring)', description: 'Dynatrace pour l\'observabilité complète', order: 9, active: true },
        { code: 'grafana_loki', label: 'Grafana Loki', label_fr: 'Grafana Loki (Observabilité Spécialisée)', label_en: 'Grafana Loki (Specialized Observability)', description: 'Grafana Loki pour les logs', order: 10, active: true },
        { code: 'grafana_tempo', label: 'Grafana Tempo', label_fr: 'Grafana Tempo (Observabilité Spécialisée)', label_en: 'Grafana Tempo (Specialized Observability)', description: 'Grafana Tempo pour le tracing', order: 11, active: true },
        { code: 'jaeger', label: 'Jaeger', label_fr: 'Jaeger (Observabilité Spécialisée)', label_en: 'Jaeger (Specialized Observability)', description: 'Jaeger pour le distributed tracing', order: 12, active: true },
        { code: 'opentelemetry', label: 'OpenTelemetry', label_fr: 'OpenTelemetry (Observabilité Spécialisée)', label_en: 'OpenTelemetry (Specialized Observability)', description: 'OpenTelemetry pour l\'observabilité standardisée', order: 13, active: true },
        { code: 'sentry', label: 'Sentry', label_fr: 'Sentry (Observabilité Spécialisée)', label_en: 'Sentry (Specialized Observability)', description: 'Sentry pour le monitoring d\'erreurs', order: 14, active: true },
        { code: 'elastic_co', label: 'Elastic.co', label_fr: 'Elastic.co (Elasticsearch, Logstash, Kibana)', label_en: 'Elastic.co (Elasticsearch, Logstash, Kibana)', description: 'Elastic.co pour la recherche et l\'analyse de données', order: 15, active: true },
      ],
    },
    {
      key: 'COMPLIANCE_TYPES',
      category: 'DD',
      entity: 'Hosting',
      formLabel: 'Conformité & Réglementation',
      description: 'Types de conformité et réglementation (CIEC) - Choix multiple',
      values: [
        { code: 'rgpd_conforme', label: 'RGPD - Conforme', label_fr: 'RGPD & Confidentialité des Données - Conforme', label_en: 'GDPR & Data Privacy - Compliant', description: 'Conforme au RGPD', order: 1, active: true },
        { code: 'rgpd_non_conforme', label: 'RGPD - Non Conforme', label_fr: 'RGPD & Confidentialité des Données - Non conforme', label_en: 'GDPR & Data Privacy - Non-Compliant', description: 'Non conforme au RGPD', order: 2, active: true },
        { code: 'banking_conforme', label: 'Normes Bancaires - Conforme', label_fr: 'Normes Bancaires (EBICS, SEPA, etc.) - Conforme', label_en: 'Banking Standards (EBICS, SEPA, etc.) - Compliant', description: 'Conforme aux normes bancaires', order: 3, active: true },
        { code: 'banking_non_conforme', label: 'Normes Bancaires - Non Conforme', label_fr: 'Normes Bancaires (EBICS, SEPA, etc.) - Non conforme', label_en: 'Banking Standards (EBICS, SEPA, etc.) - Non-Compliant', description: 'Non conforme aux normes bancaires', order: 4, active: true },
        { code: 'health_conforme', label: 'Santé/Social - Conforme', label_fr: 'Certifications Spécifiques Santé/Social (Ségur, HDS) - Conforme', label_en: 'Health/Social Certifications (Ségur, HDS) - Compliant', description: 'Conforme aux certifications santé/social', order: 5, active: true },
        { code: 'health_non_conforme', label: 'Santé/Social - Non Conforme', label_fr: 'Certifications Spécifiques Santé/Social (Ségur, HDS) - Non conforme', label_en: 'Health/Social Certifications (Ségur, HDS) - Non-Compliant', description: 'Non conforme aux certifications santé/social', order: 6, active: true },
        { code: 'quality_conforme', label: 'Qualité/Caisse - Conforme', label_fr: 'Certifications Qualité/Caisse (NF525, Datadock/Qualiopi) - Conforme', label_en: 'Quality/Cash Register Certifications (NF525, Datadock/Qualiopi) - Compliant', description: 'Conforme aux certifications qualité/caisse', order: 7, active: true },
        { code: 'quality_non_conforme', label: 'Qualité/Caisse - Non Conforme', label_fr: 'Certifications Qualité/Caisse (NF525, Datadock/Qualiopi) - Non conforme', label_en: 'Quality/Cash Register Certifications (NF525, Datadock/Qualiopi) - Non-Compliant', description: 'Non conforme aux certifications qualité/caisse', order: 8, active: true },
        { code: 'sox_conforme', label: 'SOX/SOC1 - Conforme', label_fr: 'Conformité Financière (SOX/SOC1) - Conforme', label_en: 'Financial Compliance (SOX/SOC1) - Compliant', description: 'Conforme à SOX/SOC1', order: 9, active: true },
        { code: 'sox_non_conforme', label: 'SOX/SOC1 - Non Conforme', label_fr: 'Conformité Financière (SOX/SOC1) - Non conforme', label_en: 'Financial Compliance (SOX/SOC1) - Non-Compliant', description: 'Non conforme à SOX/SOC1', order: 10, active: true },
        { code: 'pdp_conforme', label: 'Facturation Électronique - Conforme', label_fr: 'Facturation Électronique (PDP) - Conforme', label_en: 'Electronic Invoicing (PDP) - Compliant', description: 'Conforme à la facturation électronique', order: 11, active: true },
        { code: 'pdp_non_conforme', label: 'Facturation Électronique - Non Conforme', label_fr: 'Facturation Électronique (PDP) - Non conforme', label_en: 'Electronic Invoicing (PDP) - Non-Compliant', description: 'Non conforme à la facturation électronique', order: 12, active: true },
        { code: 'nf525_conforme', label: 'NF525 - Conforme', label_fr: 'NF525 (Certification AFNOR) - Conforme', label_en: 'NF525 (AFNOR Certification) - Compliant', description: 'Conforme à la certification NF525', order: 13, active: true },
        { code: 'nf525_non_conforme', label: 'NF525 - Non Conforme', label_fr: 'NF525 (Certification AFNOR) - Non conforme', label_en: 'NF525 (AFNOR Certification) - Non-Compliant', description: 'Non conforme à la certification NF525', order: 14, active: true },
        { code: 'infra_critical_conforme', label: 'Infrastructure Critique - Conforme', label_fr: 'Risque d\'Infrastructure Critique - Conforme', label_en: 'Critical Infrastructure Risk - Compliant', description: 'Conforme aux exigences d\'infrastructure critique', order: 15, active: true },
        { code: 'infra_critical_non_conforme', label: 'Infrastructure Critique - Non Conforme', label_fr: 'Risque d\'Infrastructure Critique - Non conforme', label_en: 'Critical Infrastructure Risk - Non-Compliant', description: 'Non conforme aux exigences d\'infrastructure critique', order: 16, active: true },
      ],
    },
    {
      key: 'SECURITY_MECHANISMS',
      category: 'DD',
      entity: 'SecurityProfile',
      formLabel: 'Mécanismes de Cybersécurité',
      description: 'Mécanismes de cybersécurité (CIEC) - Choix multiple',
      values: [
        { code: 'mfa_sso', label: 'Authentification Forte (MFA/SSO)', label_fr: 'Authentification forte activée (MFA, SSO)', label_en: 'Strong Authentication Enabled (MFA, SSO)', description: 'Authentification multi-facteurs ou SSO activée', order: 1, active: true },
        { code: 'patching', label: 'Gestion des Patchs', label_fr: 'Gestion des patchs', label_en: 'Patch Management', description: 'Gestion des correctifs de sécurité', order: 2, active: true },
        { code: 'encrypt_transit', label: 'Chiffrement en Transit', label_fr: 'Chiffrement en transit', label_en: 'Encryption in Transit', description: 'Chiffrement des données en transit', order: 3, active: true },
        { code: 'encrypt_rest', label: 'Chiffrement au Repos', label_fr: 'Chiffrement au repos', label_en: 'Encryption at Rest', description: 'Chiffrement des données au repos', order: 4, active: true },
        { code: 'privilege_access', label: 'Gestion des Accès Privilégiés', label_fr: 'Gestion des accès à privilèges', label_en: 'Privileged Access Management', description: 'Gestion des accès privilégiés (PAM)', order: 5, active: true },
        { code: 'pentest', label: 'Tests de Sécurité', label_fr: 'Tests de sécurité réalisés (e.g., tests de pénétration)', label_en: 'Security Tests Performed (e.g., Penetration Tests)', description: 'Tests de pénétration réalisés', order: 6, active: true },
        { code: 'reverse_proxy', label: 'Reverse Proxy', label_fr: 'Reverse proxy', label_en: 'Reverse Proxy', description: 'Reverse proxy configuré', order: 7, active: true },
        { code: 'waf', label: 'Firewall Applicatif', label_fr: 'Firewall applicatif', label_en: 'Web Application Firewall', description: 'Firewall applicatif (WAF)', order: 8, active: true },
        { code: 'https_certs', label: 'Certificats HTTPS Automatisés', label_fr: 'Certificats HTTPS automatisés', label_en: 'Automated HTTPS Certificates', description: 'Certificats HTTPS renouvelés automatiquement', order: 9, active: true },
      ],
    },
    {
      key: 'IP_OWNERSHIP_CLEAR',
      category: 'DD',
      entity: 'Solution',
      formLabel: 'Clear IP Ownership',
      description: 'Clarté de la propriété intellectuelle',
      values: [
        { code: 'Yes', label: 'Oui', label_fr: 'Oui', label_en: 'Yes', description: 'Propriété intellectuelle claire', order: 1, active: true },
        { code: 'No', label: 'Non', label_fr: 'Non', label_en: 'No', description: 'Propriété intellectuelle non claire', order: 2, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 3, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 4, active: true },
      ],
    },
    {
      key: 'LICENSE_COMPLIANCE_ASSURED',
      category: 'DD',
      entity: 'Solution',
      formLabel: 'License Compliance Assured',
      description: 'Conformité des licences assurée',
      values: [
        { code: 'Yes', label: 'Oui', label_fr: 'Oui', label_en: 'Yes', description: 'Conformité des licences assurée', order: 1, active: true },
        { code: 'No', label: 'Non', label_fr: 'Non', label_en: 'No', description: 'Conformité des licences non assurée', order: 2, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 3, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 4, active: true },
      ],
    },
    {
      key: 'DEVOPS_AUTOMATION_LEVEL',
      category: 'DD',
      entity: 'DevelopmentMetrics',
      formLabel: 'DevOps Automation Level',
      description: 'Niveau d\'automatisation DevOps/CI/CD',
      values: [
        { code: 'None', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Aucune automatisation', order: 1, active: true },
        { code: 'Manual', label: 'Manuelle', label_fr: 'Manuelle', label_en: 'Manual', description: 'Automatisation manuelle', order: 2, active: true },
        { code: 'Partial CI', label: 'CI Partiel', label_fr: 'CI Partiel', label_en: 'Partial CI', description: 'Intégration continue partielle', order: 3, active: true },
        { code: 'Full CI/CD', label: 'CI/CD Complet', label_fr: 'CI/CD Complet', label_en: 'Full CI/CD', description: 'Intégration et déploiement continus complets', order: 4, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 5, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 6, active: true },
      ],
    },
    {
      key: 'SDLC_PROCESS',
      category: 'DD',
      entity: 'DevelopmentMetrics',
      formLabel: 'SDLC Process',
      description: 'Processus de développement logiciel (SDLC)',
      values: [
        { code: 'Scrum', label: 'Scrum', label_fr: 'Scrum', label_en: 'Scrum', description: 'Méthodologie Scrum', order: 1, active: true },
        { code: 'Kanban', label: 'Kanban', label_fr: 'Kanban', label_en: 'Kanban', description: 'Méthodologie Kanban', order: 2, active: true },
        { code: 'Waterfall', label: 'Waterfall', label_fr: 'Cascade', label_en: 'Waterfall', description: 'Méthodologie en cascade', order: 3, active: true },
        { code: 'Agile', label: 'Agile', label_fr: 'Agile', label_en: 'Agile', description: 'Méthodologie Agile', order: 4, active: true },
        { code: 'Hybrid', label: 'Hybride', label_fr: 'Hybride', label_en: 'Hybrid', description: 'Méthodologie hybride', order: 5, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 6, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 7, active: true },
      ],
    },
    {
      key: 'DOCUMENTATION_LEVEL',
      category: 'DD',
      entity: 'CodeBase',
      formLabel: 'Documentation Level',
      description: 'Niveau de documentation du code',
      values: [
        { code: 'High', label: 'Élevé', label_fr: 'Élevé', label_en: 'High', description: 'Documentation complète et détaillée', order: 1, active: true },
        { code: 'Medium', label: 'Moyen', label_fr: 'Moyen', label_en: 'Medium', description: 'Documentation moyenne', order: 2, active: true },
        { code: 'Low', label: 'Faible', label_fr: 'Faible', label_en: 'Low', description: 'Documentation minimale', order: 3, active: true },
        { code: 'None', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Aucune documentation', order: 4, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 5, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 6, active: true },
      ],
    },
    {
      key: 'API_DOCUMENTATION_QUALITY',
      category: 'DD',
      entity: 'Solution',
      formLabel: 'API Documentation Quality',
      description: 'Qualité de la documentation des APIs',
      values: [
        { code: 'High', label: 'Élevée', label_fr: 'Élevée', label_en: 'High', description: 'Documentation API complète et détaillée', order: 1, active: true },
        { code: 'Medium', label: 'Moyenne', label_fr: 'Moyenne', label_en: 'Medium', description: 'Documentation API moyenne', order: 2, active: true },
        { code: 'Low', label: 'Faible', label_fr: 'Faible', label_en: 'Low', description: 'Documentation API minimale', order: 3, active: true },
        { code: 'None', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Aucune documentation API', order: 4, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 5, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 6, active: true },
      ],
    },
    {
      key: 'PATCHING_TYPES',
      category: 'DD',
      entity: 'SecurityProfile',
      formLabel: 'Gestion des Patchs',
      description: 'Types de gestion des patchs de sécurité',
      values: [
        { code: 'ad_hoc', label: 'Ad Hoc', label_fr: 'Ad Hoc', label_en: 'Ad Hoc', description: 'Gestion des patchs à la demande', order: 1, active: true },
        { code: 'scheduled', label: 'Planifiée', label_fr: 'Planifiée', label_en: 'Scheduled', description: 'Gestion des patchs planifiée', order: 2, active: true },
        { code: 'automated', label: 'Automatisée', label_fr: 'Automatisée', label_en: 'Automated', description: 'Gestion des patchs automatisée', order: 3, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 4, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 5, active: true },
      ],
    },
    {
      key: 'PENTEST_FREQ',
      category: 'DD',
      entity: 'SecurityProfile',
      formLabel: 'Fréquence des Tests de Pénétration',
      description: 'Fréquence des tests de pénétration',
      values: [
        { code: 'never', label: 'Jamais', label_fr: 'Jamais', label_en: 'Never', description: 'Aucun test de pénétration', order: 1, active: true },
        { code: 'annual', label: 'Annuel', label_fr: 'Annuel', label_en: 'Annual', description: 'Tests de pénétration annuels', order: 2, active: true },
        { code: 'quarterly', label: 'Trimestriel', label_fr: 'Trimestriel', label_en: 'Quarterly', description: 'Tests de pénétration trimestriels', order: 3, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 4, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 5, active: true },
      ],
    },
    {
      key: 'VULN_MGMT',
      category: 'DD',
      entity: 'SecurityProfile',
      formLabel: 'Gestion des Vulnérabilités',
      description: 'Types de gestion des vulnérabilités',
      values: [
        { code: 'none', label: 'Aucune', label_fr: 'Aucune', label_en: 'None', description: 'Aucune gestion des vulnérabilités', order: 1, active: true },
        { code: 'manual', label: 'Manuelle', label_fr: 'Manuelle', label_en: 'Manual', description: 'Gestion manuelle des vulnérabilités', order: 2, active: true },
        { code: 'automated', label: 'Automatisée', label_fr: 'Automatisée', label_en: 'Automated', description: 'Gestion automatisée des vulnérabilités', order: 3, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 4, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 5, active: true },
      ],
    },
    {
      key: 'DISASTER_RECOVERY_PLAN',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Plan de Reprise après Sinistre',
      description: 'Types de plans de reprise après sinistre',
      values: [
        {
          code: 'Documented',
          label: 'Documenté',
          label_fr: 'Plan documenté',
          label_en: 'Documented plan',
          description: 'Plan de reprise après sinistre formalisé et documenté',
          order: 1,
          active: true,
        },
        {
          code: 'Tested',
          label: 'Testé régulièrement',
          label_fr: 'Plan testé régulièrement',
          label_en: 'Regularly tested plan',
          description: 'Plan documenté et testé régulièrement (ex: au moins une fois par an)',
          order: 2,
          active: true,
        },
        {
          code: 'None',
          label: 'Aucun plan',
          label_fr: 'Aucun plan formel',
          label_en: 'No formal plan',
          description: 'Aucun plan de reprise après sinistre formellement défini',
          order: 3,
          active: true,
        },
        {
          code: 'TBD',
          label: 'TBD',
          label_fr: 'À déterminer',
          label_en: 'TBD',
          description: 'À déterminer',
          order: 4,
          active: true,
        },
        {
          code: 'N/A',
          label: 'N/A',
          label_fr: 'Non applicable',
          label_en: 'N/A',
          description: 'Non applicable',
          order: 5,
          active: true,
        },
      ],
    },
    {
      key: 'RESTORATION_TEST_FREQUENCY',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Fréquence des Tests de Restauration',
      description: 'Fréquence des tests de restauration de sauvegarde',
      values: [
        { code: 'annual', label: 'Annuel', label_fr: 'Annuel', label_en: 'Annual', description: 'Tests de restauration annuels', order: 1, active: true },
        { code: 'quarterly', label: 'Trimestriel', label_fr: 'Trimestriel', label_en: 'Quarterly', description: 'Tests de restauration trimestriels', order: 2, active: true },
        { code: 'never', label: 'Jamais', label_fr: 'Jamais', label_en: 'Never', description: 'Aucun test de restauration', order: 3, active: true },
        { code: 'TBD', label: 'TBD', label_fr: 'À déterminer', label_en: 'TBD', description: 'À déterminer', order: 4, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'Non applicable', label_en: 'N/A', description: 'Non applicable', order: 5, active: true },
      ],
    },
    {
      key: 'BACKUP_SCHEDULE',
      category: 'DD',
      entity: 'Environment',
      formLabel: 'Planification des Sauvegardes',
      description: 'Fréquence des sauvegardes',
      values: [
        { code: 'TBD', label: 'TBD', label_fr: 'TBD', label_en: 'TBD', description: 'À déterminer', order: 1, active: true },
        { code: 'N/A', label: 'N/A', label_fr: 'N/A', label_en: 'N/A', description: 'Non applicable', order: 2, active: true },
        { code: 'Quotidienne', label: 'Quotidienne', label_fr: 'Quotidienne', label_en: 'Daily', description: 'Sauvegarde quotidienne', order: 3, active: true },
        { code: 'Bi-quotidienne', label: 'Bi-quotidienne', label_fr: 'Bi-quotidienne', label_en: 'Twice Daily', description: 'Sauvegarde deux fois par jour', order: 4, active: true },
        { code: 'Hebdomadaire', label: 'Hebdomadaire', label_fr: 'Hebdomadaire', label_en: 'Weekly', description: 'Sauvegarde hebdomadaire', order: 5, active: true },
        { code: 'Bi-hebdomadaire', label: 'Bi-hebdomadaire', label_fr: 'Bi-hebdomadaire', label_en: 'Bi-weekly', description: 'Sauvegarde bi-hebdomadaire', order: 6, active: true },
        { code: 'Monthly', label: 'Monthly', label_fr: 'Mensuelle', label_en: 'Monthly', description: 'Sauvegarde mensuelle', order: 7, active: true },
        { code: 'Bi-Monthly', label: 'Bi-Monthly', label_fr: 'Bi-mensuelle', label_en: 'Bi-Monthly', description: 'Sauvegarde bi-mensuelle', order: 8, active: true },
        { code: 'Other', label: 'Other', label_fr: 'Autre', label_en: 'Other', description: 'Autre fréquence', order: 9, active: true },
      ],
    },
  ];

  for (const lookup of lookups) {
    // Récupérer le lookup existant pour préserver les valeurs ajoutées manuellement
    const existingLookup = await LookupModel.findOne({ key: lookup.key });
    
    if (existingLookup) {
      // Fusionner les valeurs : garder les valeurs existantes et ajouter les nouvelles si elles n'existent pas
      const existingCodes = new Set(existingLookup.values.map((v: any) => v.code));
      const newValues = lookup.values.filter((v: any) => !existingCodes.has(v.code));
      
      // Mettre à jour avec les valeurs fusionnées
      await LookupModel.findOneAndUpdate(
        { key: lookup.key },
        {
          ...lookup,
          values: [...existingLookup.values, ...newValues],
        },
        { new: true }
      );
    } else {
      // Créer le lookup s'il n'existe pas
      await LookupModel.findOneAndUpdate(
        { key: lookup.key },
        lookup,
        { upsert: true, new: true }
      );
    }
  }

  console.log('✅ Lookups P1 et DD initialisés avec succès');
}

